"""
scripts/knowledge.py

Ingest SHAP explanations + domain docs into ChromaDB.

Run this after each training run to refresh the RAG knowledge base.
The assistant's answer quality improves directly with how fresh this data is.

What gets ingested:
    1. Domain knowledge docs   — src/knowledge/docs/*.txt and *.md
    2. SHAP explanations       — generated by running AgentExplainer on rollout states

Usage:
    python scripts/build_knowledge_base.py
    python scripts/build_knowledge_base.py --shap_only
    python scripts/build_knowledge_base.py --docs_only
"""

import argparse
import logging
import pickle

import numpy as np
import yaml

logging.basicConfig(level=logging.INFO, format="%(asctime)s | %(levelname)s | %(message)s")
log = logging.getLogger(__name__)


def main(args):
    from src.knowledge.ingestion import build_knowledge_chunks
    from src.knowledge.vector_store import VectorStore
    from src.agent.rl_agent import PPOAgent
    from src.explainability.shap_explainer import build_agent_explainer

    with open(args.config) as f:
        cfg = yaml.safe_load(f)

    vs = VectorStore(persist_dir=cfg.get("vector_store_dir", "outputs/vector_store"))

    # ── Optionally refresh SHAP chunks ────────────────────────────────────────
    shap_results = None
    if not args.docs_only:
        log.info("Generating SHAP explanations from rollout states...")
        shap_results = _generate_shap_results(cfg)

    # ── Build and upsert chunks ───────────────────────────────────────────────
    docs_dir = cfg.get("knowledge_docs_dir", "src/knowledge/docs")

    if args.shap_only:
        from src.knowledge.ingestion import ingest_shap_results
        chunks = ingest_shap_results(shap_results or [])
    else:
        chunks = build_knowledge_chunks(
            shap_results = shap_results,
            docs_dir     = docs_dir,
        )

    if not chunks:
        log.warning("No chunks produced — check your docs_dir and rollout_states.npy.")
        return

    # Refresh SHAP chunks only (don't wipe domain docs)
    if not args.docs_only and shap_results:
        log.info("Clearing stale agent_decision chunks before re-ingestion...")
        vs.delete_by_source_type("agent_decision")

    upserted = vs.upsert(chunks)
    log.info(f"Knowledge base updated. Total docs in store: {vs.count()}")


def _generate_shap_results(cfg: dict) -> list[dict]:
    """
    Load PPO agent + rollout states → run AgentExplainer on a sample.
    Returns a list of SHAP result dicts ready for ingestion.
    """

    from src.agent.rl_agent import PPOAgent
    from src.explainability.shap_explainer import build_agent_explainer

    rollout_path = "outputs/models/rollout_states.npy"
    ppo_path     = "outputs/models/ppo_inventory.pt"

    try:
        rollout_states = np.load(rollout_path)                    # (N, 10)
        agent          = PPOAgent(state_dim=10, n_actions=11)
        agent.load("ppo_inventory.pt")
        agent.policy.eval()

        explainer = build_agent_explainer(agent, rollout_states)

        # Explain a sample of states — 20 is enough for a useful knowledge base
        results  = []
        item_ids = cfg["data"].get("store_ids", ["CA_1"])

        for i, obs in enumerate(rollout_states[:20]):
            action    = agent.predict(obs)
            order_qty = action * 10
            result    = explainer.explain(
                obs          = obs,
                action_taken = action,
                order_qty    = order_qty,
                item_id      = item_ids[i % len(item_ids)],
                step         = i,
            )
            results.append(result)

        log.info(f"Generated {len(results)} SHAP explanations.")
        return results

    except FileNotFoundError as e:
        log.warning(f"Could not generate SHAP results: {e}")
        log.warning("Run train_ppo.py first to generate rollout_states.npy.")
        return []


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Build InventIQ knowledge base")
    parser.add_argument("--config",    default="config.yaml")
    parser.add_argument("--shap_only", action="store_true",
                        help="Ingest only SHAP results, skip domain docs")
    parser.add_argument("--docs_only", action="store_true",
                        help="Ingest only domain docs, skip SHAP")
    main(parser.parse_args())